### ISSUE TITLE
元数据拉取回来后解压到media里面的子目录全是“?"

### ISSUE THREAD

**Issue by lsykc** [monlor/docker-xiaoya#219]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

日志报错几万条类似下面
2024/07/21 18:59:52 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/???/????????????????????/10 ????_1080p.strm
2024/07/21 18:59:52 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/???/????????????????????/10 ????_1080p.nfo
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/9??????.strm
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/9??????.nfo
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/8????.strm
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/8????.nfo
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/85?????.strm
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/85?????.nfo
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/82??????.strm
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/82??????.nfo
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/7????????.strm
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/7????????.nfo
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/79???????.strm
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/79???????.nfo
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/6????.strm
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/6????.nfo
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/69??????.strm
2024/07/21 18:59:37 | stderr | ERROR: Can not delete output file : No such file or directory : ./??/??/????????/69??????.nfo

### 设备 (请填写以下信息)

Linux

**Comment by monlor** [comment]
再试一下，我现在没有会员，元数据下载很慢，没法测试

**Comment by hanlihanshaobo** [comment]
> 再试一下，我现在没有会员，元数据下载很慢，没法测试

xiaoya那边已经有了针对开了svip接触限速的办法了，大佬啥时候跟进下

**Comment by Jeafly** [comment]
已出现同样情况

**Comment by monlor** [comment]
我现在都没发测试，下载元数据速度太慢了🤣

**Comment by monlor** [comment]
export VERSION=v1.2.14 && bash -c "$(curl -fsSL https://raw.githubusercontent.com/monlor/docker-xiaoya/main/install.sh)"

先安装旧版本吧

**Comment by shadowless520** [comment]
/xiaoya/data/media文件夹下已经更新了strm和元数据，但是emby里面却找不到是什么原因啊？

**Comment by monlor** [comment]
> /xiaoya/data/media文件夹下已经更新了strm和元数据，但是emby里面却找不到是什么原因啊？

安装的什么版本

**Comment by shadowless520** [comment]
> > 但是/xiaoya/data/media文件夹下已经更新了strm和元数据，emby里面却找不到什么原因啊？
> 
> 安装的什么版本

最新版本，可以播放，但是我看emby媒体库里面都没有设置文件夹路径，是不是需要添加然后扫库？

**Comment by monlor** [comment]
> > > 但是/xiaoya/data/media文件夹下已经更新了strm和元数据，emby里面却找不到什么原因啊？
> 
> > 
> 
> > 安装的什么版本
> 
> 
> 
> 最新版本，可以播放，但是我看emby媒体库里面都没有设置文件夹路径，是不是需要添加然后扫库？

有些数据对不上是正常的 更新频率不一样

**Comment by Jeafly** [comment]
> export VERSION=v1.2.14 && bash -c "$(curl -fsSL https://raw.githubusercontent.com/monlor/docker-xiaoya/main/install.sh)"
> 
> 先安装旧版本吧

我是用的docker compose出现的？？情况，文件内容如下
```yaml
services:
  alist:
    container_name: xiaoya
    image: ghcr.io/monlor/xiaoya-alist:latest
    volumes:
      - /mnt/user/appdata/xiaoya:/data
    ports:
      - "5678:5678"
      - "2345:2345"
      - "2346:2346"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
  metadata:
    container_name: xiaoya-metadata
    image: ghcr.io/monlor/xiaoya-metadata:latest
    env_file:
      - .env
    volumes:
      - /mnt/user/appdata/xiaoya:/etc/xiaoya
      - /mnt/user/cache/xiaoya/media:/media/xiaoya
      - /mnt/user/cache/xiaoya/config:/media/config
      - /mnt/user/cache/xiaoya/cache:/media/config/cache
      - /mnt/user/cache/xiaoya/meta:/media/temp
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default
  emby:
    container_name: xiaoya-emby
    image: ghcr.io/monlor/xiaoya-embyserver:latest
    env_file:
      - .env
    depends_on:
      - metadata
      - alist
    volumes:
      - /mnt/user/cache/xiaoya/media:/media
      - /mnt/user/cache/xiaoya/config:/config
      - /mnt/user/cache/xiaoya/cache:/cache
    ports:
      - "6908:6908"
    restart: unless-stopped
    networks:
      - default

networks:
  default:

```
