### ISSUE TITLE
[BUG]: 元数据镜像容器似乎有问题metadata

### ISSUE THREAD

**Issue by star7th** [monlor/docker-xiaoya#295]
### 提交检查

- [X] 我已经搜索过 Issues，没有找到类似问题
- [X] 我已经使用[百度](https://www.baidu.com)或[谷歌](https://www.google.com)搜索过，没有找到类似问题
- [X] 我已经检查过[常见问题](https://github.com/monlor/docker-xiaoya/blob/main/Questions.md)，没有找到类似问题

### 描述 bug

当我进入元数据容器metadata的命令行，执行 curl -s --fail "http://alist:5678/api/public/settings" ，则无法获得结果。
测试 curl www.baidu.com 也无果。怀疑是不是镜像出错了。
xiaoya服务目前能正常打开，5678端口可以访问网页。
看了下其他问题，似乎也听过安装不了emby的情况。所以烦请作者有空的时候检查下是不是metadata镜像有问题。

### 重现步骤

我的docker compse配置文件如下。

```

services:
  alist:
    image: ghcr.io/monlor/xiaoya-alist:latest
    volumes:
      - xiaoya:/data
    ports:
      - "5678:5678"
      - "2345:2345"
      - "2346:2346"
    env_file:
      - env
    restart: unless-stopped
    networks:
      - default
  metadata:
    image: ghcr.io/monlor/xiaoya-metadata:latest
    env_file:
      - env
    volumes:
      - xiaoya:/etc/xiaoya
      - media:/media/xiaoya
      - config:/media/config
      - cache:/media/config/cache
      - meta:/media/temp
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default
  emby:
    image: ghcr.io/monlor/xiaoya-embyserver:latest
    env_file:
      - env
    depends_on:
      - metadata
      - alist
    volumes:
      - media:/media
      - config:/config
      - cache:/cache
    ports:
      - "6908:6908"
    restart: unless-stopped
    networks:
      - default

networks:
  default:

volumes:
  xiaoya:
  media:
  config:
  meta:
  cache:


```

### 设备 (请填写以下信息)

Linux
